table 'Cases per US State'
	lineageTag: 84645845-bc6c-49cc-9ea7-c8ea616fd893

	measure 'Cases DoD%' =
			
			VAR __PREV_DAY =
				CALCULATE(
					SUM('Cases per US State'[Incremental cases]),
					DATEADD('Dates'[Date], -1, DAY)
				)
			RETURN
				DIVIDE(
					SUM('Cases per US State'[Incremental cases]) - __PREV_DAY,
					__PREV_DAY
				)
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		lineageTag: 1dc14c77-1846-426a-b057-bd9cf49bb09e

	measure 'IncrementalCases Mvg Avg' =
			
			CALCULATE (
			    SUM( 'Cases per US State'[Incremental cases] )/7,
			    DATESINPERIOD (
			        'Dates'[Date],
			        min('Dates'[Date] ),
			        -7,
			        DAY
			    ))
		lineageTag: 0f8ee781-4c2e-40b1-bb7c-9687054862d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cases per million 7d avg' =
			
			var numCases = CALCULATE (
			    SUM( 'Cases per US State'[Incremental cases] )/7,
			    DATESINPERIOD (
			        'Dates'[Date],
			        min('Dates'[Date] ),
			        -7,
			        DAY
			    ))
			
			var pop = SUM(States[Population])
			return DIVIDE(numCases, pop)*1000000
		lineageTag: b76596ee-fc60-436d-80c0-991b333092ac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cumulative ppl vaccinated per 100' = COALESCE(SUM('Cases per US State'[People fully vaccinated per hundred]),0)
		formatString: 0
		lineageTag: 8e37fe77-b0d6-4e69-b7ea-39beaa768325

	measure 'DailyVaccinations Mvg Avg' =
			
			CALCULATE (
			    SUM( 'Cases per US State'[daily_vaccinations] )/7,
			    DATESINPERIOD (
			        'Dates'[Date],
			        min('Dates'[Date] ),
			        -7,
			        DAY
			    ))
		lineageTag: 2f4ab824-5105-4ac3-92bb-bbf5aeeabd51

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Vaccines distributed' =
			
			var totalDistributed = SUM('Cases per US State'[total_distributed])
			var latestDate = MAX('OWID COVID data'[date])
			var latestVaccineTotal = CALCULATE(AVERAGE('Cases per US State'[total_distributed]), 'Cases per US State'[Date] = latestDate)
			return if(HASONEVALUE(Dates[Date]), totalDistributed, latestVaccineTotal)
		formatString: #,0
		lineageTag: c2fbd0d9-37da-4ef1-91e8-35546b15ea3a

	measure 'daily_vaccinations running total in Date' =
			
			CALCULATE(
				SUM('Cases per US State'[daily_vaccinations]),
				FILTER(
					ALLSELECTED('Dates'[Date]),
					ISONORAFTER('Dates'[Date], MAX('Dates'[Date]), DESC)
				)
			)
		formatString: 0
		lineageTag: 27402a5a-1a84-4852-b632-c60b3530f840

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "RunningTotal"
				}

	measure 'Full vaccinations per hundred' = COALESCE(AVERAGE( 'Cases per US State'[People fully vaccinated per hundred]),0)
		lineageTag: 482905b0-ce15-4e6f-9a5e-f0243b787687

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cumulative cases per 100' = AVERAGE('Cases per US State'[CumulativeCases]) / AVERAGE(States[Population]) * 100
		lineageTag: 1ae10977-aca4-44dd-95cb-d58333f0557b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Change from 12/27' =
			
			VAR __BASELINE_VALUE =
				CALCULATE(
					[IncrementalCases Mvg Avg] //AVERAGE('Cases per US State'[Incremental Cases]),
			        ,ALLSELECTED(Dates[Start of week]),
					'Dates'[Start of week] = DATE(2020, 12, 27)
				)
			VAR __MEASURE_VALUE = [IncrementalCases Mvg Avg] //AVERAGE('Cases per US State'[Incremental Cases])
			VAR __PCT_Diff =
				IF(
					NOT ISBLANK(__MEASURE_VALUE),
					DIVIDE(__MEASURE_VALUE - __BASELINE_VALUE, __BASELINE_VALUE)
				)
			return __PCT_Diff
		formatString: 0%;-0%;0%
		lineageTag: 8254934f-9881-43b5-9fa3-825c4af5b167

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "PercentageDifferenceFrom"
				}

	measure 'Ratio fully vaccinated' = MAX('Cases per US State'[People fully vaccinated per hundred]) / MAX('Cases per US State'[people_vaccinated_per_hundred])
		lineageTag: 0d21c362-3966-491b-9116-142a4cd94a00

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Fully Vacc''d' = ```
			
			CALCULATE(
			    MAX('Cases per US State'[People fully vaccinated per hundred])/100
			    ,ALLSELECTED(Dates[Start of week]),'Dates'[Start of week] = DATE(2021, 4, 11))
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f9ca0180-dc8c-4bd6-9ea9-583fd5dfd35a

	measure '% One+ Shots' = MAX('Cases per US State'[people_vaccinated_per_hundred])/100
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2818cd80-3451-4dd1-9ad7-d4851cfb131b

	measure 'Daily Change US (for formatting)' = ```
			
			VAR __PREV_DAY =
				CALCULATE(
					[Cases per million 7d avg],
					DATEADD('Dates'[Date], -2, DAY)
				)
			var changeFromPrevDay = DIVIDE([Cases per million 7d avg] - __PREV_DAY, __PREV_DAY)
			
			    RETURN changeFromPrevDay
				
			
			    
			```
		lineageTag: 96a8c923-fb69-4752-8701-373db15b9686

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Key
		dataType: string
		lineageTag: 239c8969-6367-4e2e-b309-5b46e5a92f13
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 747a4b4b-6fed-44ce-9ed1-06fa5286e790
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CumulativeCases
		dataType: int64
		formatString: 0
		lineageTag: 604615ba-a850-4093-9fac-790626f3e649
		summarizeBy: sum
		sourceColumn: CumulativeCases

		annotation SummarizationSetBy = Automatic

	column CumulativeDeaths
		dataType: int64
		formatString: 0
		lineageTag: d7385357-12b8-4b04-bae8-74417bd62c8c
		summarizeBy: sum
		sourceColumn: CumulativeDeaths

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 377dfeda-3c05-450f-909c-d39bf102d21b
		summarizeBy: none
		sourceColumn: State

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Incremental cases'
		dataType: int64
		formatString: 0
		lineageTag: 737cc7a8-8622-4e91-965c-1af2c3501c2f
		summarizeBy: sum
		sourceColumn: Incremental cases

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column IncrementalDeaths
		dataType: int64
		formatString: 0
		lineageTag: 9d542f37-3379-4c96-92fe-100c625c3fff
		summarizeBy: sum
		sourceColumn: IncrementalDeaths

		annotation SummarizationSetBy = Automatic

	column total_vaccinations
		dataType: int64
		formatString: 0
		lineageTag: e48aeb00-e6c0-4cab-a95b-cf3b06627717
		summarizeBy: sum
		sourceColumn: total_vaccinations

		annotation SummarizationSetBy = Automatic

	column total_distributed
		dataType: int64
		formatString: 0
		lineageTag: b875bf61-7dc6-4170-be7a-a872b015409e
		summarizeBy: sum
		sourceColumn: total_distributed

		annotation SummarizationSetBy = Automatic

	column people_vaccinated
		dataType: int64
		formatString: 0
		lineageTag: 686beb8a-c40f-4f2e-ab9b-ed0fc14df4c1
		summarizeBy: sum
		sourceColumn: people_vaccinated

		annotation SummarizationSetBy = Automatic

	column 'People fully vaccinated per hundred'
		dataType: double
		isHidden
		lineageTag: eb4cf93e-f90a-48f9-90e4-ce8070ebf464
		summarizeBy: sum
		sourceColumn: People fully vaccinated per hundred

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_vaccinations_per_hundred
		dataType: double
		lineageTag: bc926e34-397b-40b3-82ba-80d3cec8beef
		summarizeBy: sum
		sourceColumn: total_vaccinations_per_hundred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column people_fully_vaccinated
		dataType: int64
		formatString: 0
		lineageTag: e64faa6b-56d7-4c0c-bc21-28980e6c1cbc
		summarizeBy: sum
		sourceColumn: people_fully_vaccinated

		annotation SummarizationSetBy = Automatic

	column people_vaccinated_per_hundred
		dataType: double
		lineageTag: b5838b6f-0d22-431a-a7ef-92f456a293d8
		summarizeBy: sum
		sourceColumn: people_vaccinated_per_hundred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column distributed_per_hundred
		dataType: double
		lineageTag: 0a1a3998-91a9-4157-b0a2-39228c5dcae3
		summarizeBy: sum
		sourceColumn: distributed_per_hundred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column daily_vaccinations_raw
		dataType: double
		lineageTag: 1d7bff25-4252-4fd1-bef4-a5bf24f7b894
		summarizeBy: sum
		sourceColumn: daily_vaccinations_raw

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column daily_vaccinations
		dataType: int64
		formatString: 0
		lineageTag: d0414c27-d0a5-4a2c-98ac-08acdd12e50e
		summarizeBy: sum
		sourceColumn: daily_vaccinations

		annotation SummarizationSetBy = Automatic

	column daily_vaccinations_per_million
		dataType: int64
		formatString: 0
		lineageTag: effbee37-d7f1-4095-8560-152ffe32ef3a
		summarizeBy: sum
		sourceColumn: daily_vaccinations_per_million

		annotation SummarizationSetBy = Automatic

	column share_doses_used
		dataType: double
		lineageTag: ed750331-75a6-49d5-8586-adec996f76b2
		summarizeBy: sum
		sourceColumn: share_doses_used

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Cases per US State-bb7db7f9-5922-49a8-9cff-73daedaae272' = m
		mode: import
		source = ```
				let
				    Source = Sql.Database("<private-sql-server>.database.windows.net", "researchlab", [Query="SELECT [Key]#(lf),[GeoLevel]#(lf),[CountyName]#(lf)#(tab)#(tab),[Date]#(lf)#(tab)#(tab),[Date_Day1Case]#(lf)#(tab)#(tab),[Date_Day1Death]#(lf)#(tab)#(tab),[Date_Max]#(lf)                ,[Days_from_Day1Case]#(lf)                ,[Days_from_Day1Death]#(lf)#(tab)#(tab),[CumulativeCases]#(lf)#(tab)#(tab),[CumulativeDeaths]#(lf)#(tab)#(tab),[IncrementalCases]#(lf)#(tab)#(tab),[IncrementalDeaths]#(lf)#(tab)#(tab),[IncrementalCasesNoNegatives]#(lf)#(tab)#(tab),[IncrementalDeathsNoNegatives]#(lf)  FROM [COVID19].[vw_WHO_USAFacts_BingTracker_Data_Combined]"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Date", type date}, {"Date_Day1Case", type date}, {"Date_Day1Death", type date}, {"Date_Max", type date}, {"CumulativeCases", Int64.Type}, {"CumulativeDeaths", Int64.Type}, {"IncrementalCases", Int64.Type}, {"IncrementalDeaths", Int64.Type}, {"IncrementalCasesNoNegatives", Int64.Type}, {"IncrementalDeathsNoNegatives", Int64.Type}, {"Days_from_Day1Case", Int64.Type}, {"Days_from_Day1Death", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([GeoLevel] = "State")),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"CountyName", "GeoLevel", "Date_Day1Case", "Date_Day1Death", "Date_Max", "Days_from_Day1Case", "Days_from_Day1Death", "IncrementalCases", "IncrementalDeaths"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"IncrementalCasesNoNegatives", "IncrementalCases"}, {"IncrementalDeathsNoNegatives", "IncrementalDeaths"}}),
				    #"Inserted Text After Delimiter" = Table.AddColumn(#"Renamed Columns1", "Text After Delimiter", each Text.AfterDelimiter([Key], "_"), type text),
				    #"Filtered Rows1" = Table.SelectRows(#"Inserted Text After Delimiter", each ([Key] <> null)),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows1",{{"Text After Delimiter", "State"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"State", "Date"}, us_state_vaccinations, {"location", "date"}, "us_state_vaccinations", JoinKind.LeftOuter),
				    #"Expanded us_state_vaccinations" = Table.ExpandTableColumn(#"Merged Queries", "us_state_vaccinations", {"total_vaccinations", "total_distributed", "people_vaccinated", "people_fully_vaccinated_per_hundred", "total_vaccinations_per_hundred", "people_fully_vaccinated", "people_vaccinated_per_hundred", "distributed_per_hundred", "daily_vaccinations_raw", "daily_vaccinations", "daily_vaccinations_per_million", "share_doses_used"}, {"total_vaccinations", "total_distributed", "people_vaccinated", "people_fully_vaccinated_per_hundred", "total_vaccinations_per_hundred", "people_fully_vaccinated", "people_vaccinated_per_hundred", "distributed_per_hundred", "daily_vaccinations_raw", "daily_vaccinations", "daily_vaccinations_per_million", "share_doses_used"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Expanded us_state_vaccinations",{{"IncrementalCases", "Incremental cases"}, {"people_fully_vaccinated_per_hundred", "People fully vaccinated per hundred"}}),
				    #"Fix New York spike" = Table.ReplaceValue(#"Renamed Columns2",each [Incremental cases],each if [Key]="State_New York" and [Incremental cases]=20184 then 7154 else [Incremental cases],Replacer.ReplaceValue,{"Incremental cases"}),
				    #"Fix Minnesota spike" = Table.ReplaceValue(#"Fix New York spike",each [Incremental cases],each 
				        if [Key]="State_Minnesota" and [Incremental cases]=0 then 1651 
				        else if [Key]="State_Missouri" and [Incremental cases]=50328 then 512 
				        else [Incremental cases],Replacer.ReplaceValue,{"Incremental cases"}),
				    #"Fix New Jersey spiek" = Table.ReplaceValue(#"Fix Minnesota spike",each [Incremental cases],each if [Key]="State_New Jersey" and [Incremental cases]=51092 then 4215 else [Incremental cases],Replacer.ReplaceValue,{"Incremental cases"})
				in
				    #"Fix New Jersey spiek"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

