table 'OWID COVID data'
	lineageTag: eb4a509c-f885-4ce5-aaae-18ff315630ac

	measure 'Total cases per mil' = MAX('OWID COVID data'[Total cases per million])
		displayFolder: 1. Health metrics
		lineageTag: 265ae5d4-d984-45b8-b40f-26c73bb0983d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total deaths p/m' = MAX('OWID COVID data'[Total deaths per million])
		lineageTag: 6fd3e636-848e-487b-9b8e-daa54f03cb39

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Latest vaccinations per million' =
			
			var latestDate = MAX('OWID COVID data'[date])
			return CALCULATE(AVERAGE('OWID COVID data'[New vaccinations smoothed per million]), 'OWID COVID data'[Date] = latestDate)
		lineageTag: 420dcac0-c054-4934-b7f2-5a46315744fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% of Population Vaccinated' =
			
			if(HASONEVALUE(Countries[Country]), max('OWID COVID data'[People vaccinated per hundred]), [Total vaccinations running total in Date]/SUM(Countries[Population])*100)/100
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 99bc781c-d3c1-4e90-812e-b67314de7769

	measure 'Cases 7d Avg per country' = ```
			
			var sevenDayPeriod = DATESINPERIOD (
			        'Dates'[Date],
			        min('Dates'[Date] ),
			        -7,
			        DAY
			    )
			return CALCULATE (
			    SUM( 'Cases per country'[IncrementalCases] )/7,
			    sevenDayPeriod
			    )
			
			
			```
		lineageTag: 022c138d-cce2-4e2d-9748-c49339711cc2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cases 7d Mvg Avg per million' = ```
			
			var mvgAvgCases = CALCULATE (
			    SUM( 'OWID COVID data'[New cases] )/7,
			    DATESINPERIOD (
			        'Dates'[Date],
			        min('Dates'[Date] ),
			        -7,
			        DAY
			    ))
			var population = SUM(Countries[Population])
			return  DIVIDE(mvgAvgCases, population)  *1000000 
			```
		lineageTag: ede5fc46-8205-4b7c-84fe-0955884ebdd7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Change in cases WoW%' = ```
			
			VAR __PREV_WEEK =
				CALCULATE(
					[Cases 7d Avg per country],
					DATEADD('Dates'[Date], -7, DAY)
				)
			RETURN 
				min(DIVIDE(
					[Cases 7d Avg per country] - __PREV_WEEK,
					__PREV_WEEK
				), 5)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5b321565-1460-4598-96ae-2316b190d8b6

	measure 'Total vaccinations' = SUM('OWID COVID data'[new_vaccinations])
		lineageTag: 74d08807-16b2-4f87-a482-13165134b64e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total vaccinations running total in Date' =
			
			CALCULATE(
				[Total vaccinations],
				FILTER(
					ALLSELECTED('Dates'[Date]),
					ISONORAFTER('Dates'[Date], MAX('Dates'[Date]), DESC)
				)
			)
		lineageTag: 56de7125-28ae-4c93-931d-401481c9ec5c

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "RunningTotal"
				}

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Daily Change (for formatting)' = ```
			
			VAR __PREV_DAY =
				CALCULATE(
					[Cases 7d Mvg Avg per million],
					DATEADD('Dates'[Date], -2, DAY)
				)
			var changeFromPrevDay = DIVIDE([Cases 7d Mvg Avg per million] - __PREV_DAY, __PREV_DAY)
			
			    RETURN changeFromPrevDay
				
			
			    
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9163a331-358c-4f57-90b0-90df7741dd83

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MonthOverMonth"
				}

	column iso_code
		dataType: string
		lineageTag: 776c6894-cf05-429b-9b72-18e88c4dd361
		summarizeBy: none
		sourceColumn: iso_code

		annotation SummarizationSetBy = Automatic

	column continent
		dataType: string
		isHidden
		lineageTag: 90948b62-232f-48b5-96eb-476707d9dde6
		summarizeBy: none
		sourceColumn: continent

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 5e00e8fa-92df-4b85-8386-9b08c51a76fa
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		isHidden
		formatString: m/d/yyyy
		lineageTag: 7e5caf9f-a900-431e-ad7e-47d72e166ff8
		summarizeBy: none
		sourceColumn: date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Total cases'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: fa6df2d5-bd32-4bb3-a949-1b228f1879dd
		summarizeBy: sum
		sourceColumn: Total cases

		annotation SummarizationSetBy = Automatic

	column 'New cases'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a96e0135-5853-4a81-a8e7-5e875279926d
		summarizeBy: sum
		sourceColumn: New cases

		annotation SummarizationSetBy = Automatic

	column 'New cases smoothed'
		dataType: double
		isHidden
		lineageTag: ad1faff7-ae19-4819-8751-c4ba5589e454
		summarizeBy: sum
		sourceColumn: New cases smoothed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total deaths'
		dataType: int64
		formatString: 0
		lineageTag: ce6f229a-ecb2-44bc-8023-7f01024e1b78
		summarizeBy: sum
		sourceColumn: Total deaths

		annotation SummarizationSetBy = Automatic

	column 'New deaths'
		dataType: int64
		formatString: 0
		lineageTag: 83de57e6-5403-4036-80a1-82ea4df8e175
		summarizeBy: sum
		sourceColumn: New deaths

		annotation SummarizationSetBy = Automatic

	column 'New deaths smoothed'
		dataType: double
		lineageTag: 3d20718f-be66-4f68-9f39-f81733e886e1
		summarizeBy: sum
		sourceColumn: New deaths smoothed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total cases per million'
		dataType: double
		isHidden
		lineageTag: 7292b3af-7055-4528-8394-a21455ab2c25
		summarizeBy: sum
		sourceColumn: Total cases per million

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'New cases per million'
		dataType: double
		isHidden
		lineageTag: 33670e65-5071-4e98-9516-640417837f44
		summarizeBy: sum
		sourceColumn: New cases per million

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'New cases smoothed per million'
		dataType: double
		isHidden
		lineageTag: 8821b10e-fe7d-4157-bf6e-b78bb95f07e6
		summarizeBy: sum
		sourceColumn: New cases smoothed per million

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total deaths per million'
		dataType: double
		lineageTag: 42096684-1096-4720-9685-2ddaa757e906
		summarizeBy: sum
		sourceColumn: Total deaths per million

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'New deaths per million'
		dataType: double
		lineageTag: 6cc865cb-4140-40dc-a052-da2764ce7f9f
		summarizeBy: sum
		sourceColumn: New deaths per million

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'New deaths smoothed per million'
		dataType: double
		lineageTag: 8d65cb44-8e1e-4708-9e8e-d01e4a6edd3f
		summarizeBy: sum
		sourceColumn: New deaths smoothed per million

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Reproduction rate'
		dataType: double
		lineageTag: ce1b4568-dbdb-4c96-a101-481ea9c39c5e
		summarizeBy: sum
		sourceColumn: Reproduction rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ICU patients'
		dataType: double
		lineageTag: f6c5ff11-4fcc-4d11-ac91-619b5c33ec4d
		summarizeBy: average
		sourceColumn: ICU patients

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ICU patients per million'
		dataType: double
		lineageTag: 016674f4-3787-4790-9d6d-8cf0c31eaed2
		summarizeBy: average
		sourceColumn: ICU patients per million

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Hospital patients'
		dataType: double
		lineageTag: 6ef96c11-f1bc-4754-a11f-5866ced39bad
		summarizeBy: average
		sourceColumn: Hospital patients

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Hospital patients per million'
		dataType: double
		lineageTag: 40ea4180-a7f8-4279-97e8-18e0d7e27253
		summarizeBy: average
		sourceColumn: Hospital patients per million

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Weekly ICU admissions'
		dataType: double
		lineageTag: 03e91eea-0a76-4160-9e63-033ea47012b3
		summarizeBy: sum
		sourceColumn: Weekly ICU admissions

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Weekly ICU admissisions per million'
		dataType: double
		lineageTag: 14d24ab7-f852-44f7-8df2-853226c95b4f
		summarizeBy: sum
		sourceColumn: Weekly ICU admissisions per million

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weekly_hosp_admissions
		dataType: double
		lineageTag: f9ee4fb6-cde6-4ca9-a2e3-c268a7727340
		summarizeBy: sum
		sourceColumn: weekly_hosp_admissions

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Weekly hospital admissions per million'
		dataType: double
		lineageTag: 1ae8be0e-71b0-4b81-a0c6-85380e314a50
		summarizeBy: sum
		sourceColumn: Weekly hospital admissions per million

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column new_tests
		dataType: double
		lineageTag: 4cdd028c-90bc-47b2-a5ce-5483235a4b4c
		summarizeBy: sum
		sourceColumn: new_tests

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_tests
		dataType: double
		lineageTag: 00ea608d-de08-44a5-b11e-0ea9456aa28a
		summarizeBy: sum
		sourceColumn: total_tests

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total tests per thousand'
		dataType: double
		lineageTag: 5fccdc9c-8c12-4c2a-90e5-320e80dd47d9
		summarizeBy: sum
		sourceColumn: Total tests per thousand

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'New tests per thousands'
		dataType: double
		lineageTag: 773c6017-d320-42f3-8e00-af8aa900ea39
		summarizeBy: sum
		sourceColumn: New tests per thousands

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column new_tests_smoothed
		dataType: double
		lineageTag: 4c9c1e68-777e-4a03-84bd-d88ccf5433f1
		summarizeBy: sum
		sourceColumn: new_tests_smoothed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column new_tests_smoothed_per_thousand
		dataType: double
		lineageTag: 799d6f52-8184-4371-8078-6f72ee69c8cf
		summarizeBy: sum
		sourceColumn: new_tests_smoothed_per_thousand

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column positive_rate
		dataType: double
		lineageTag: eb25feb1-c25e-416e-8f48-cdc18059b3f5
		summarizeBy: sum
		sourceColumn: positive_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tests_per_case
		dataType: double
		isHidden
		lineageTag: 82803a38-e8a9-4a2e-b372-9708d428c937
		summarizeBy: sum
		sourceColumn: tests_per_case

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tests_units
		dataType: string
		lineageTag: badf84a2-1a55-4f7f-8e57-a3962486a587
		summarizeBy: none
		sourceColumn: tests_units

		annotation SummarizationSetBy = Automatic

	column total_vaccinations
		dataType: double
		lineageTag: da2310c3-17ad-43d2-b1e6-777f64722767
		summarizeBy: sum
		sourceColumn: total_vaccinations

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column people_vaccinated
		dataType: double
		lineageTag: 7f8086c7-0b35-41d1-ac35-cf451b03839a
		summarizeBy: sum
		sourceColumn: people_vaccinated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column people_fully_vaccinated
		dataType: double
		lineageTag: b5a25ac4-b164-40da-ab90-b92de8cc54c7
		summarizeBy: sum
		sourceColumn: people_fully_vaccinated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column new_vaccinations
		dataType: double
		lineageTag: 1fb32d94-94c1-4a82-9601-c589f34037ec
		summarizeBy: sum
		sourceColumn: new_vaccinations

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column new_vaccinations_smoothed
		dataType: double
		lineageTag: 461763ff-9915-4d27-8bfc-636a7514a16c
		summarizeBy: sum
		sourceColumn: new_vaccinations_smoothed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total vaccinations per hundred'
		dataType: double
		lineageTag: b72da3b1-18e8-4ef6-9694-71f6684f4a29
		summarizeBy: sum
		sourceColumn: Total vaccinations per hundred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'People vaccinated per hundred'
		dataType: double
		lineageTag: f906502f-449a-4baf-9231-58639e49c52a
		summarizeBy: sum
		sourceColumn: People vaccinated per hundred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'People fully vaccinated per hundred'
		dataType: double
		lineageTag: 112d9102-c770-42e9-a9f2-feb82ce39d10
		summarizeBy: sum
		sourceColumn: People fully vaccinated per hundred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'New vaccinations smoothed per million'
		dataType: double
		lineageTag: 0afaedff-d8d3-4075-9f90-b16b14e4894d
		summarizeBy: sum
		sourceColumn: New vaccinations smoothed per million

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column stringency_index
		dataType: double
		lineageTag: 2e4dea4e-4fb4-4d2a-ad35-14e4862abced
		summarizeBy: average
		sourceColumn: stringency_index

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Population
		dataType: int64
		formatString: 0
		lineageTag: 6f8b589c-e5ba-4798-bc43-2dfc418fe93d
		summarizeBy: average
		sourceColumn: Population

		annotation SummarizationSetBy = User

	column 'Population density'
		dataType: double
		lineageTag: 7d959d1f-4771-41c8-b5fc-6b96c6ebbdfd
		summarizeBy: average
		sourceColumn: Population density

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Median age'
		dataType: double
		lineageTag: c1eb6044-57d2-4eec-b351-6c8ba2698f29
		summarizeBy: average
		sourceColumn: Median age

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Aged 65 and older'
		dataType: double
		isHidden
		displayFolder: 1. Health metrics
		lineageTag: 894e5d5f-afd6-4fd5-98a3-25826efdccce
		summarizeBy: average
		sourceColumn: Aged 65 and older

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Aged 70 and old'
		dataType: double
		displayFolder: 1. Health metrics
		lineageTag: 5174d187-c5c2-41d3-bb6b-82a4ef11f0ac
		summarizeBy: average
		sourceColumn: Aged 70 and old

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'GDP per capita'
		dataType: double
		lineageTag: 1fcee0d6-3097-457c-8a23-4335ae9d1ca9
		summarizeBy: average
		sourceColumn: GDP per capita

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Extreme poverty'
		dataType: double
		lineageTag: 158489cb-dffe-49b1-a8b2-cdc2df087a20
		summarizeBy: average
		sourceColumn: Extreme poverty

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cardiovascular death rate'
		dataType: double
		displayFolder: 1. Health metrics
		lineageTag: 524e223c-fcb1-400d-919e-7fb94d137a1a
		summarizeBy: average
		sourceColumn: Cardiovascular death rate

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Diabetes prevalence'
		dataType: double
		displayFolder: 1. Health metrics
		lineageTag: fc6f3ba6-861e-45e3-bb18-d44237e867af
		summarizeBy: average
		sourceColumn: Diabetes prevalence

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Female smoking rate'
		dataType: double
		displayFolder: 1. Health metrics
		lineageTag: eb12bade-d1a1-40a2-a477-3f3755a2f35d
		summarizeBy: average
		sourceColumn: Female smoking rate

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Male smoking rate'
		dataType: double
		displayFolder: 1. Health metrics
		lineageTag: fcaf71b3-41a3-45ef-bff5-4d4b26698a48
		summarizeBy: average
		sourceColumn: Male smoking rate

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Handwashing facilities availalbe'
		dataType: double
		displayFolder: 1. Health metrics
		lineageTag: 5d9fa644-9442-4a94-895c-e018a02dc996
		summarizeBy: average
		sourceColumn: Handwashing facilities availalbe

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Hospital beds per thousand'
		dataType: double
		lineageTag: 3241fa51-ff60-41e1-9dfc-227315b38e8b
		summarizeBy: average
		sourceColumn: Hospital beds per thousand

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Life expectancy'
		dataType: double
		lineageTag: 50eadb6a-1e5b-4ae1-8fe8-602ff51b29f6
		summarizeBy: average
		sourceColumn: Life expectancy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column human_development_index
		dataType: double
		lineageTag: bd94a7cd-a00a-4ab3-a2df-152d1987cd1e
		summarizeBy: average
		sourceColumn: human_development_index

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'OWID COVID data-2b68fb8c-8c71-4e9b-8b71-d75435e50838' = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://covid.ourworldindata.org/data/owid-covid-data.csv"),[Delimiter=",", Columns=59, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"iso_code", type text}, {"continent", type text}, {"location", type text}, {"date", type date}, {"total_cases", Int64.Type}, {"new_cases", Int64.Type}, {"new_cases_smoothed", type number}, {"total_deaths", Int64.Type}, {"new_deaths", Int64.Type}, {"new_deaths_smoothed", type number}, {"total_cases_per_million", type number}, {"new_cases_per_million", type number}, {"new_cases_smoothed_per_million", type number}, {"total_deaths_per_million", type number}, {"new_deaths_per_million", type number}, {"new_deaths_smoothed_per_million", type number}, {"reproduction_rate", type number}, {"icu_patients", type number}, {"icu_patients_per_million", type number}, {"hosp_patients", type number}, {"hosp_patients_per_million", type number}, {"weekly_icu_admissions", type number}, {"weekly_icu_admissions_per_million", type number}, {"weekly_hosp_admissions", type number}, {"weekly_hosp_admissions_per_million", type number}, {"new_tests", type number}, {"total_tests", type number}, {"total_tests_per_thousand", type number}, {"new_tests_per_thousand", type number}, {"new_tests_smoothed", type number}, {"new_tests_smoothed_per_thousand", type number}, {"positive_rate", type number}, {"tests_per_case", type number}, {"tests_units", type text}, {"total_vaccinations", type number}, {"people_vaccinated", type number}, {"people_fully_vaccinated", type number}, {"new_vaccinations", type number}, {"new_vaccinations_smoothed", type number}, {"total_vaccinations_per_hundred", type number}, {"people_vaccinated_per_hundred", type number}, {"people_fully_vaccinated_per_hundred", type number}, {"new_vaccinations_smoothed_per_million", type number}, {"stringency_index", type number}, {"population", Int64.Type}, {"population_density", type number}, {"median_age", type number}, {"aged_65_older", type number}, {"aged_70_older", type number}, {"gdp_per_capita", type number}, {"extreme_poverty", type number}, {"cardiovasc_death_rate", type number}, {"diabetes_prevalence", type number}, {"female_smokers", type number}, {"male_smokers", type number}, {"handwashing_facilities", type number}, {"hospital_beds_per_thousand", type number}, {"life_expectancy", type number}, {"human_development_index", type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{
				        {"total_cases", "Total cases"},
				        {"new_cases", "New cases"}, {"new_cases_smoothed", "New cases smoothed"}, {"total_deaths", "Total deaths"}, {"new_deaths", "New deaths"}, {"new_deaths_smoothed", "New deaths smoothed"}, {"total_cases_per_million", "Total cases per million"}, {"new_cases_per_million", "New cases per million"}, {"new_cases_smoothed_per_million", "New cases smoothed per million"}, {"total_deaths_per_million", "Total deaths per million"}, {"new_deaths_per_million", "New deaths per million"}, {"new_deaths_smoothed_per_million", "New deaths smoothed per million"}, {"reproduction_rate", "Reproduction rate"}, {"icu_patients", "ICU patients"}, {"icu_patients_per_million", "ICU patients per million"}, {"hosp_patients", "Hospital patients"}, {"hosp_patients_per_million", "Hospital patients per million"}, {"weekly_icu_admissions", "Weekly ICU admissions"}, {"weekly_icu_admissions_per_million", "Weekly ICU admissisions per million"}, {"weekly_hosp_admissions_per_million", "Weekly hospital admissions per million"},{"total_tests_per_thousand", "Total tests per thousand"}, {"new_tests_per_thousand", "New tests per thousands"}, {"total_vaccinations_per_hundred", "Total vaccinations per hundred"}, {"people_vaccinated_per_hundred", "People vaccinated per hundred"}, {"people_fully_vaccinated_per_hundred", "People fully vaccinated per hundred"}, {"new_vaccinations_smoothed_per_million", "New vaccinations smoothed per million"}, {"population", "Population"}, {"population_density", "Population density"}, {"median_age", "Median age"}, {"aged_65_older", "Aged 65 and older"}, {"aged_70_older", "Aged 70 and old"}, {"gdp_per_capita", "GDP per capita"}, {"extreme_poverty", "Extreme poverty"}, {"cardiovasc_death_rate", "Cardiovascular death rate"}, {"diabetes_prevalence", "Diabetes prevalence"}, {"female_smokers", "Female smoking rate"}, {"male_smokers", "Male smoking rate"}, {"handwashing_facilities", "Handwashing facilities availalbe"}, {"hospital_beds_per_thousand", "Hospital beds per thousand"}, {"life_expectancy", "Life expectancy"}
				
				    })
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

