table Opportunities
	lineageTag: 574e7ea3-1c8d-44ef-8571-714b66f865c7

	measure 'Revenue Won' = ```
			
			 CALCULATE(
			     SUMX(Opportunities, Opportunities[Value]),
			     FILTER(Opportunities, Opportunities[Status] = "Won")
			 )
			```
		formatString: \$#,0.0;(\$#,0.0);\$#,0.0
		lineageTag: 4175e2ae-8428-461a-854b-9a68cf5b5b8c

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Revenue In Pipeline' = ```
			
			VAR Revenue =
			    CALCULATE (
			        SUMX ( Opportunities, Opportunities[Value] ),
			        FILTER (
			            Opportunities,
			            Opportunities[Status] = "Open"
			            && VALUE(LEFT(Opportunities[PipelineStep],1)) >=2
			        )
			    )
			RETURN
			    Revenue + ( Revenue * ( 'Opportunity Forecast Adjustment'[Forecast Adjustment Value] / 100 ) )
			
			```
		formatString: \$#,0.0;(\$#,0.0);\$#,0.0
		lineageTag: 1322f812-7712-498e-9f4d-ba6b80052388

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Forecast %' = (([Revenue Won]+[Revenue In Pipeline]))/ [Rev Goal]
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 78a5c219-6674-49f8-a2c5-4da21114763d

	measure Forecast = ([Revenue Won]+[Revenue In Pipeline])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: f3eb5c0a-9667-445a-b762-e4e9f911c533

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Opportunity Count In Pipeline' = ```
			
			    CALCULATE (
			        COUNT( Opportunities[Value] ),
			        FILTER (
			            Opportunities,
			            Opportunities[Status] = "Open"
			              --  && Opportunities[PipelineStep] IN { "3-Pipeline", "4-Mandate", "5-Close" }
			        )
			    )
			
			```
		formatString: #,0
		lineageTag: b4effa85-1aa3-4f33-a3ef-07ec57b59c0f

	measure 'Opportunity Count' =
			
			COUNTAX(Opportunities,TRUE())
		formatString: #,0
		lineageTag: f9cdd5b7-71b0-42ca-b100-d957cbdaa375

	measure 'Count of Won' = ```
			
			COUNTAX(
			    FILTER(
			        KEEPFILTERS(Opportunities),Opportunities[Status] = "Won"
			        ),
			    Opportunities[OpportunitySeq]
			    ) 
			```
		formatString: #,0
		lineageTag: 61908284-58b6-4ce1-b980-2cd65b89fafd

	measure 'Count of Lost' = ```
			
			COUNTAX(
			    FILTER(
			        KEEPFILTERS(Opportunities),Opportunities[Status] = "Lost"
			        ),
			    Opportunities[OpportunitySeq]
			    ) 
			```
		formatString: #,0
		lineageTag: 0995fcc4-bb40-4d35-aac9-9ecf60f69bbe

	measure 'Close %' = [Count of Won]/([Count of Won]+[Count of Lost])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 938be727-4972-4ef9-a507-da6a1d898703

	measure 'Revenue Open' =
			
			CALCULATE(
			     SUMX(Opportunities, Opportunities[Value]),
			     FILTER(Opportunities, Opportunities[Status] = "Open")
			 )
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d8ffa47c-94b4-4585-9170-43b31ec2dd1d

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Budget
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 556ef9d9-7d5a-45a7-8e33-2105b953a479
		summarizeBy: sum
		sourceColumn: Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Topic
		dataType: string
		lineageTag: 32f9cb08-35d6-4241-93ca-78b7407d77e1
		summarizeBy: none
		sourceColumn: Topic

		annotation SummarizationSetBy = Automatic

	column 'Purchase Process'
		dataType: string
		lineageTag: 00abd866-3af0-434f-8635-f746c83e5694
		summarizeBy: none
		sourceColumn: Purchase Process

		annotation SummarizationSetBy = Automatic

	column 'Decision Maker Identified'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 70e6bcc8-4f3b-44c9-a8fd-c6ab1dc077e3
		summarizeBy: none
		sourceColumn: Decision Maker Identified

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: f9b0d395-092e-4efb-9bac-3e9c3e90267c
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column PipelineStep
		dataType: string
		lineageTag: 635fffe3-c82b-44dd-a7f4-fdfc182c16ba
		summarizeBy: none
		sourceColumn: PipelineStep

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f6ca5c5b-b98b-4e28-be48-e41e58ff1f47
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column CloseDate
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 84b71727-1241-4f96-9e2d-48cbe6d61599
		summarizeBy: none
		sourceColumn: CloseDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Opportunity Created On'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: cb4340a2-6933-4682-b181-ce1ab700d1c4
		summarizeBy: none
		sourceColumn: Opportunity Created On

		variation Variation
			isDefault
			relationship: 31b31781-e688-46e4-87c6-e17c1b83fcac
			defaultHierarchy: LocalDateTable_b0573d09-ef3e-45e2-9f39-8a331c91c6c3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Weeks Open' =
			
			ABS (
			    DATEDIFF (
			        Opportunities[Opportunity Created On],
			        IF (
			            ISBLANK ( Opportunities[CloseDate] ) = TRUE (),
			            TODAY (),
			            Opportunities[CloseDate]
			        ),
			        WEEK
			    )
			)
		formatString: 0
		lineageTag: 306e46c3-251b-4fb0-852e-2a4a1fe836e8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column DaysToClose
		dataType: int64
		formatString: 0
		lineageTag: 75f86392-0397-4e9c-810b-4e8132ca2b51
		summarizeBy: sum
		sourceColumn: DaysToClose

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 7dee90ec-9e9f-482c-886d-27ad10f69ca9
		summarizeBy: average
		sourceColumn: Discount

		annotation SummarizationSetBy = User

	column Probability
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 5e2b16c7-e253-45ab-b986-dc70108d374b
		summarizeBy: average
		sourceColumn: Probability

		annotation SummarizationSetBy = User

	column Rating
		dataType: string
		lineageTag: 04da9d56-63a7-4837-8b29-3a0af0bd068a
		summarizeBy: none
		sourceColumn: Rating

		annotation SummarizationSetBy = Automatic

	column 'Days Remaining In Pipeline' = IF(Opportunities[Status]="Open", DATEDIFF(TODAY(),Opportunities[CloseDate],DAY),0)
		formatString: 0
		lineageTag: 4f4a0d24-8d74-4d68-94cc-c673541c22dd
		summarizeBy: average

		annotation SummarizationSetBy = User

	column 'Probability (raw)'
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 03731a21-07fc-4287-8519-0f79116053e5
		summarizeBy: average
		sourceColumn: Probability (raw)

		annotation SummarizationSetBy = User

	column AccountSeq
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 964185da-1291-4026-a472-33f798d3a5d6
		summarizeBy: none
		sourceColumn: AccountSeq

		annotation SummarizationSetBy = Automatic

	column 'Opportunity Owner Name'
		dataType: string
		lineageTag: 488d6008-b867-4e7d-bdd2-2502564a381c
		summarizeBy: none
		sourceColumn: Opportunity Owner Name

		annotation SummarizationSetBy = Automatic

	column OpportunitySeq
		dataType: int64
		formatString: 0
		lineageTag: c8a5e37b-7f5b-449f-a431-86bbba34a109
		summarizeBy: sum
		sourceColumn: OpportunitySeq

		annotation SummarizationSetBy = Automatic

	column ProductSeq
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 109d74f6-1df8-4cdb-9749-9cb58c5c8fc2
		summarizeBy: none
		sourceColumn: ProductSeq

		annotation SummarizationSetBy = Automatic

	column SystemUserSeq
		dataType: string
		isHidden
		lineageTag: 23825680-4031-48c9-9356-830b3ad86257
		summarizeBy: none
		sourceColumn: SystemUserSeq

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 208ff9bd-0f23-4e66-80c9-9a272bcad6c5
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column CampaignSeq
		dataType: string
		isHidden
		lineageTag: b5ed8f8b-36c2-44db-b64e-e3ac67bb36b2
		summarizeBy: none
		sourceColumn: CampaignSeq

		annotation SummarizationSetBy = Automatic

	column 'Campaign Name'
		dataType: string
		lineageTag: c0f2ab4e-e8a8-4683-ae52-8f783faaa370
		summarizeBy: none
		sourceColumn: Campaign Name

		annotation SummarizationSetBy = Automatic

	column Blank = BLANK()
		formatString: 0
		lineageTag: 6fae75b6-0c16-4c05-89cd-86c0df25fcb0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Opportunities-2905f1f8-aef9-42b6-b178-4b43efaa2633 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\misewell\OneDrive - Microsoft\Documents\GitHub\ContosoBI\Contoso - Generic\Contoso - PowerBI Source Data.xlsx"), null, true),
				    OpportunityTbl_Table = Source{[Item="OpportunityTbl",Kind="Table"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(OpportunityTbl_Table,{"OpportunitySeq", "CreatedonDate", "DaysToClose", "CloseDate", "SystemUserSeq", "Opportunity Owner Name", "AccountSeq", "ProductSeq", "ProductName", "CampaignSeq", "Campaign Name", "Budget", "Topic", "Purchase Process", "Decision Maker Identified", "Discount", "Value", "PipelineStep", "Probability (raw)", "Probability", "Rating", "Status"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"OpportunitySeq", Int64.Type}, {"CreatedonDate", type date}, {"DaysToClose", Int64.Type}, {"CloseDate", type date}, {"SystemUserSeq", type text}, {"Opportunity Owner Name", type text}, {"AccountSeq", Int64.Type}, {"ProductSeq", Int64.Type}, {"ProductName", type text}, {"Budget", Int64.Type}, {"Topic", type text}, {"Purchase Process", type text}, {"Decision Maker Identified", type logical}, {"Discount", type number}, {"Value", Int64.Type}, {"PipelineStep", type text}, {"Probability (raw)", type number}, {"Probability", type number}, {"Rating", type text}, {"Status", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"CreatedonDate", "Opportunity Created On"}, {"ProductName", "Product Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_QueryRelationships = {"columnCount":22,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Opportunities/Changed Type.{OpportunitySeq,0}","Section1/Opportunities/Changed Type.{CreatedonDate,1}","Section1/Opportunities/Changed Type.{DaysToClose,2}","Section1/Opportunities/Changed Type.{CloseDate,3}","Section1/Opportunities/Changed Type.{SystemUserSeq,4}","Section1/Opportunities/Changed Type.{Opportunity Owner Name,5}","Section1/Opportunities/Changed Type.{AccountSeq,6}","Section1/Opportunities/Changed Type.{ProductSeq,7}","Section1/Opportunities/Changed Type.{ProductName,8}","Section1/Opportunities/OpportunityTbl_Table.{CampaignSeq,10}","Section1/Opportunities/OpportunityTbl_Table.{Campaign Name,11}","Section1/Opportunities/Changed Type.{Budget,11}","Section1/Opportunities/Changed Type.{Topic,12}","Section1/Opportunities/Changed Type.{Purchase Process,13}","Section1/Opportunities/Changed Type.{Decision Maker Identified,14}","Section1/Opportunities/Changed Type.{Discount,15}","Section1/Opportunities/Changed Type.{Value,16}","Section1/Opportunities/Changed Type.{PipelineStep,17}","Section1/Opportunities/Changed Type.{Probability (raw),18}","Section1/Opportunities/Changed Type.{Probability,19}","Section1/Opportunities/Changed Type.{Rating,20}","Section1/Opportunities/Changed Type.{Status,21}"],"ColumnCount":22,"KeyColumnNames":[],"ColumnIdentities":["Section1/Opportunities/Changed Type.{OpportunitySeq,0}","Section1/Opportunities/Changed Type.{CreatedonDate,1}","Section1/Opportunities/Changed Type.{DaysToClose,2}","Section1/Opportunities/Changed Type.{CloseDate,3}","Section1/Opportunities/Changed Type.{SystemUserSeq,4}","Section1/Opportunities/Changed Type.{Opportunity Owner Name,5}","Section1/Opportunities/Changed Type.{AccountSeq,6}","Section1/Opportunities/Changed Type.{ProductSeq,7}","Section1/Opportunities/Changed Type.{ProductName,8}","Section1/Opportunities/OpportunityTbl_Table.{CampaignSeq,10}","Section1/Opportunities/OpportunityTbl_Table.{Campaign Name,11}","Section1/Opportunities/Changed Type.{Budget,11}","Section1/Opportunities/Changed Type.{Topic,12}","Section1/Opportunities/Changed Type.{Purchase Process,13}","Section1/Opportunities/Changed Type.{Decision Maker Identified,14}","Section1/Opportunities/Changed Type.{Discount,15}","Section1/Opportunities/Changed Type.{Value,16}","Section1/Opportunities/Changed Type.{PipelineStep,17}","Section1/Opportunities/Changed Type.{Probability (raw),18}","Section1/Opportunities/Changed Type.{Probability,19}","Section1/Opportunities/Changed Type.{Rating,20}","Section1/Opportunities/Changed Type.{Status,21}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

