table Owners
	lineageTag: 70f990fe-b5ba-4e53-b914-9a6dc8e15c2d

	measure 'Rev Goal' = ```
			
			VAR RevenueInPipeline =
			    CALCULATE (
			        SUMX ( Opportunities, Opportunities[Value] ),
			        FILTER (
			            Opportunities,
			            Opportunities[Status] = "Open"
			            && VALUE(LEFT(Opportunities[PipelineStep],1)) >=3
			        )
			    )
			VAR BaseGoal =  
			MROUND(([Revenue Won]+ (RevenueInPipeline*.75)),100000)    
			RETURN
			IF(BaseGoal > 0, BaseGoal, MROUND(([Revenue Won]+ (RevenueInPipeline*.75)),10000))
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 059ac849-789a-4698-801d-a415d2de84c5

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Sales owner'
		dataType: string
		lineageTag: e5d3bb04-f671-4f7a-8c1f-eb98ebf219b2
		summarizeBy: none
		sourceColumn: Sales owner

		annotation SummarizationSetBy = Automatic

	column Manager
		dataType: string
		lineageTag: 38ded122-e7d0-40cd-8632-8086592f0019
		summarizeBy: none
		sourceColumn: Manager

		annotation SummarizationSetBy = Automatic

	column SystemUserSeq
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 78f9ac7f-d017-4e2a-a320-28ae9765282e
		summarizeBy: none
		sourceColumn: SystemUserSeq

		annotation SummarizationSetBy = Automatic

	partition Owners-6403f03d-aca3-423f-9155-a1097b964223 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\misewell\OneDrive - Microsoft\Documents\GitHub\ContosoBI\Contoso - Generic\Contoso - PowerBI Source Data.xlsx"), null, true),
				    OwnerTbl_Table = Source{[Item="OwnerTbl",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(OwnerTbl_Table,{{"Owner", type text}, {"Factor", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Factor"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"SystemUserSeq", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Owner", "Sales owner"}})
				in
				    #"Renamed Columns"

	annotation PBI_QueryRelationships = {"columnCount":3,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Owners/Changed Type1.{SystemUserSeq,0}","Section1/Owners/Changed Type.{Owner,1}","Section1/Owners/OwnerTbl_Table.{Manager,2}"],"ColumnCount":3,"KeyColumnNames":[],"ColumnIdentities":["Section1/Owners/Changed Type1.{SystemUserSeq,0}","Section1/Owners/Changed Type.{Owner,1}","Section1/Owners/OwnerTbl_Table.{Manager,2}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

