table Territories
	isHidden
	lineageTag: 353b2fab-9798-4035-afca-a28f49c1412e

	column Region
		dataType: string
		lineageTag: 29b6b784-efd8-4941-ad88-46a0c98942f9
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Territory
		dataType: string
		lineageTag: d718bf26-fb5e-4e0a-bcdd-4b1089f7d40d
		summarizeBy: none
		sourceColumn: Territory

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: a77c71c4-e669-48bf-a735-0b48c22d54fa
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'State Or Province Abbreviation'
		dataType: string
		lineageTag: 3c326ba2-8b0b-4c60-9f6a-8d69e4b5ab78
		summarizeBy: none
		sourceColumn: State Or Province Abbreviation

		annotation SummarizationSetBy = Automatic

	partition Territories-cce59963-af31-4ea3-b1a5-c2b42f20283f = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\misewell\OneDrive - Microsoft\Documents\GitHub\ContosoBI\Contoso - Generic\Contoso - PowerBI Source Data.xlsx"), null, true),
				    TerritoriesTbl_Table = Source{[Item="TerritoriesTbl",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(TerritoriesTbl_Table,{{"Country", type text}, {"State Or Province Abbreviation", type text}, {"Region", type text}, {"Territory", type text}})
				in
				    #"Changed Type"

	annotation PBI_QueryRelationships = {"columnCount":4,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Territories/Changed Type.{Country,0}","Section1/Territories/Changed Type.{State Or Province Abbreviation,1}","Section1/Territories/Changed Type.{Region,2}","Section1/Territories/Changed Type.{Territory,3}"],"ColumnCount":4,"KeyColumnNames":[],"ColumnIdentities":["Section1/Territories/Changed Type.{Country,0}","Section1/Territories/Changed Type.{State Or Province Abbreviation,1}","Section1/Territories/Changed Type.{Region,2}","Section1/Territories/Changed Type.{Territory,3}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

